### ISSUE TITLE
Problem in GHCi 7.10.2 on Mac OS X

### ISSUE THREAD

**Issue by FranklinChen** [Euterpea/Euterpea#29] opened 2015-09-03 04:20 UTC
I just installed the Hackage 1.1.0 version on Mac OS X Yosemite with Cabal, but following the README instructions, I could not get the example running in GHCi:

```console
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Euterpea.Examples.MUI
Prelude Euterpea.Examples.MUI> mui5
can't load .so/.DLL for: /Users/chen/.cabal/lib/x86_64-osx-ghc-7.10.2/PortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u/libHSPortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u-ghc7.10.2.dylib (dlopen(/Users/chen/.cabal/lib/x86_64-osx-ghc-7.10.2/PortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u/libHSPortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u-ghc7.10.2.dylib, 5): Symbol not found: _kMIDIPropertyConnectionUniqueID
  Referenced from: /Users/chen/.cabal/lib/x86_64-osx-ghc-7.10.2/PortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u/libHSPortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u-ghc7.10.2.dylib
  Expected in: flat namespace
 in /Users/chen/.cabal/lib/x86_64-osx-ghc-7.10.2/PortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u/libHSPortMidi-0.1.4-CGgNDiYJqLM5nwd73Vp16u-ghc7.10.2.dylib)
```

However, things work if I just compile with GHC and run. Am I missing some setting for GHCi?

**Comment by sebeaumont** [comment] 2015-09-12 01:46
AFAIK This is due to a [regression in ghc and a bug in cabal](https://ghc.haskell.org/trac/ghc/ticket/10568) which fails to link dylibs against OS X frameworks. 
I worked around this with the following:
```
cabal install GLUT --ghc-options="-optl-Wl,-framework,GLUT" --reinstall --jobs=1
cabal install portmidi --ghc-options="-optl-Wl,-framework,CoreMIDI" --reinstall --jobs=1
```
This at least lets ghci run via (cabal repl) but there are further issues with GLUT when running the example:
```
*Euterpea> :m +Euterpea.Examples.MUI
*Euterpea Euterpea.Examples.MUI> mui5
<interactive>: user error (unknown GLUT entry glutInit)
*** Exception: thread blocked indefinitely in an MVar operation
```
Watch this space...

**Comment by FranklinChen** [comment] 2015-09-18 21:58
Yeah, following your instructions, I got just as far as this.

**Comment by FranklinChen** [comment] 2016-01-07 22:35
Any more word on this?

**Comment by samdoshi** [comment] 2016-01-08 07:34
Have you tried with 7.10.3? That's supposed to have some fixes for this...

**Comment by FranklinChen** [comment] 2016-01-08 16:00
Yes, I've built with 7.10.3, still have this problem.

**Comment by donya** [comment] 2016-03-01 15:09
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage. 

Euterpea 2 no longer depends on UISF. The MUI features that require UISF are now part of a separate, newer library called HSoM.

**Closed by donya** 2016-03-01 15:09 UTC

**Comment by FranklinChen** [comment] 2016-03-01 17:48
Thanks for the update.
