### ISSUE TITLE
Pitch does not have sane Ord instance.

### ISSUE THREAD

**Issue by alexreinking** [Euterpea/Euterpea#32] opened 2016-02-08 05:41 UTC
In ghci simply test:

    (C,4) < (C,5)

and be amazed when False is returned!

How can this be the correct behavior? Comparing on `absPitch` would make way more sense.

**Comment by donya** [comment] 2016-03-01 14:53
Euterpea 1.x (this repository) is not currently being updated. All updates are happening within the Euterpea 2 respository, although it is possible that the two repositories may be merged eventually once  Euterpea 2 is ready for hackage. Within Euterpea 2, I can't reproduce the described problem. I get (C,4) < (C,5) ==> True, which is correct.

For issues like (Bs,4) < (C,5) ==> False, which is the more common complaint, it is because Haskell's default tuple comparisons are used, and it has been that way since Euterpea was first created. Comparing based on absPitch or other methods is left for the user to decide. The reason for this is that enharmonic equivalences may be handled differently in different scenarios.

**Closed by donya** 2016-03-01 14:53 UTC
