### ISSUE TITLE
Midi generated doesn't have correct tempo settings

### ISSUE THREAD

**Issue by ilitzroth** [Euterpea/Euterpea#31] opened 2015-11-13 09:19 UTC
I've been using Euterpea for generating midi files that are then loaded in Ardour and played through a drum plugin. If I generate a midi file with tempo 96 qn I get a file where the ticks are always 96 and the tempo always 50000. 
Here's the file at tempo 60 qn
         0 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (ProgramChange (Program {fromProgram = 0}))}
         0 : Event.MetaEvent SetTempo 500000
         0 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (NoteOn (Pitch {fromPitch = 37}) (Velocity {fromVelocity = 100}))}
       192 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (NoteOff (Pitch {fromPitch = 37}) (Velocity {fromVelocity = 100}))}

And here it is at tempo 120 qn
         0 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (ProgramChange (Program {fromProgram = 0}))}
         0 : Event.MetaEvent SetTempo 500000
         0 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (NoteOn (Pitch {fromPitch = 37}) (Velocity {fromVelocity = 100}))}
        96 : Event.MIDIEvent Cons {messageChannel = Channel {fromChannel = 9}, messageBody = Voice (NoteOff (Pitch {fromPitch = 37}) (Velocity {fromVelocity = 100}))}

So instead of scaling the tempo, you scale the offsets.
I think this is wrong because the tick are ticks per quarter note -- well at tempo 120 qn t does the correct thing :-) -- and Ardour definitely handles this incorrectly. Workaround for now is always generating at tempo 120.

Also I found the lack of time signatures in Euterpea a bit strange. A waltz is not a jig.

**Comment by donya** [comment] 2016-03-01 15:01
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage. 

The effect of the Tempo modifier you have observed is not a bug; you're seeing the intended behavior. Tempo modifiers to allow for musical structures that do not adhere to the standard MIDI notion of beats and measures. The scaling of the offsets also allows for easier integration with MIDI streams. If you want write a MIDI file with a specific tempo, you can construct the music value as for 120bpm and then, within Euterpea 2, you can use a combination of the perform and toMidi functions to access the intermediate Midi type (which belongs to Codec.Midi) and alter timeDiv as desired.

**Closed by donya** 2016-03-01 15:01 UTC
